### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by hohoCode** [mrflogs/LoRA-Pro#2]
Any plan to integrate your solid Lora-PRO work into [LLAMAFACTORY ](https://github.com/hiyouga/LLaMA-Factory) , so a wider audience can enjoy this great tool?

**Comment by mrflogs** [comment]
Thank you very much for your suggestion. Currently, we are testing our existing implementation to check for any hidden bugs.
After that, we hope to submit a pull request to llama-factory, PEFT, or similar repositories if everything goes well :)
